### ISSUE TITLE
error when videocapture from gstreamer 

### ISSUE THREAD

**Issue by gaochunzy** [friendlyarm/install-opencv-in-friendlycore#1]
when I running a demo script to capture rtsp stream using cv2.VideoCapture() in python on the fire3 as following:

if __name__ == "__main__":
    print("OpenCV version: {}".format(cv2.__version__))
    gst_str = "rtspsrc location=rtsp://192.168.0.101:554/Streaming/Channels/101 protocols=GST_RTSP_LOWER_TRANS_TCP ! rtph264depay ! h264parse ! nxvideodec  ! video/x-raw, width=1280, height=720, format=(string)BGRx ! appsink"
    cap=cv2.VideoCapture(gst_str, cv2.CAP_GSTREAMER)

the error occurred and the output recorded as,

OpenCV version: 3.4.2-dev
mime type = video/x-h264
NumSps = 1, NumPps = 1, type = avcC type
node found for device nx-vpu-dec: /dev/video15
<<<<<<<<<< InitializeCodaVpu(Min=7, 1280x720) (ret = 0) >>>>>>>>>

(python:1011): GStreamer-CRITICAL **: gst_element_get_state: assertion 'GST_IS_ELEMENT (element)' failed

**Comment by friendlyarm** [comment]
please update the firmware to the version of 20190511 can solve your problem.
