### ISSUE TITLE
OpenCv cap(0) . not working ?

### ISSUE THREAD

**Issue by MyraBaba** [friendlyarm/install-opencv-in-friendlycore#2]
in c++ VideoCapture cap(0);  

gives error:

VIDIOC_QUERYCTRL: Inappropriate ioctl for device

any help ?

**Comment by fyywhy** [comment]
I have the same problem. Have you solved it？

**Comment by MyraBaba** [comment]
nope

**Comment by friendlyarm** [comment]
Hi all, 

We just updated the firmware and upgraded the camera driver from rockchip-isp10 to rockchip-isp1. 

Now the rk3399 boards (T4/M4/NEO4) can support two MIPI cameras working at the same time. 
We also provide some examples of OpenCV, I hope to be useful to you.

New firmware download url:
dl.friendlyarm.com/nanopct4

OpenCV examples:
https://github.com/friendlyarm/install-opencv-on-friendlycore/tree/rk3399/examples

**Comment by MyraBaba** [comment]
Hi @friendlyarm  if we use the new friendly-desktop-arm64 from https://drive.google.com/drive/folders/1sMzkr5Lkw7JN87zTVfUZZmvQLTIamvLA than it will work ? 

thx

**Comment by MyraBaba** [comment]
Hi,

Thanks for the update.

One of the problem that we faced with current image is the corruption if the power goes down somehow .

Armbian OS keep the minimum writing to emac to avoid this and very successful. 

How we can make the friendlycore based OS resistant to the emac or Scared corruption ?

**Comment by MyraBaba** [comment]
Hi,

Is there any image download in google drive. ?

Mega download requires registration and payment ?
