### ISSUE TITLE
How to capture video with OpenCV from CAM1320 module

### ISSUE THREAD

**Issue by alexanderfrey** [friendlyarm/install-opencv-in-friendlycore#3]
I would like to access the CAM 1320 from Python via the openCV library. Can somebody help ? Documentation is a bit sparse in the direction...

**Comment by friendlyarm** [comment]
Updating the firmware to the version of 20190511 can solve your problem:
dl.friendlyarm.com/nanopct4

We also provide some examples of OpenCV, I hope to be useful to you:
https://github.com/friendlyarm/install-opencv-on-friendlycore/tree/rk3399/examples
