### ISSUE TITLE
Problem with configuring the UVC resolution by cv::VideoCapture::set()

### ISSUE THREAD

**Issue by bodomliu** [friendlyarm/install-opencv-in-friendlycore#5]
The default resolution is 640*480.
When I try to use "cv::VideoCapture::set(CAP_PROP_FRAME_WIDTH ,1280)" to change the resolution, it doesn't work.

**Comment by chichivica** [comment]
@bodomliu 
Hi! Could share your whole opecv script where you are capturing video? 
We will have a look into your issue!

**Comment by friendlyarm** [comment]
We just updated the firmware and upgraded the camera driver from rockchip-isp10 to rockchip-isp1. 

Now the rk3399 boards (T4/M4/NEO4) can support two MIPI cameras working at the same time. 
We also provide some examples of OpenCV, I hope to be useful to you.

New firmware download url:
dl.friendlyarm.com/nanopct4

OpenCV examples:
https://github.com/friendlyarm/install-opencv-on-friendlycore/tree/rk3399/examples

isp1 wiki:
http://opensource.rock-chips.com/wiki_Rockchip-isp1
