### ISSUE TITLE
Installing snap

### ISSUE THREAD

**Issue by guyluz11** [friendlyarm/install-opencv-in-friendlycore#6]
I am trying to use snap on friendlycore OS on my NanoPi NEO.
I have install snapd with the commend `sudo apt install snapd`.

In the installation I get the following errors:

> md5sum: /etc/apparmor.d/usr.lib.snapd.snap-confine: No such file or directory
> snapd.failure.service is a disabled or a static unit, not starting it.
> snapd.snap-repair.service is a disabled or a static unit, not starting it.
> Update rpimonitor Packages Status
> E: Could not get lock /var/lib/dpkg/lock-frontend - open (11: Resource temporarily unavailable)
> E: Unable to acquire the dpkg frontend lock (/var/lib/dpkg/lock-frontend), is another process using it?
> W: Could not lock the cache file; this usually means that dpkg or another apt tool is already installing packages.  Opening in read-only mode; any changes you make to the states of packages will NOT be preserved!

And then it recognize the snap commend but when I run `sudo snap install hello-world` I get the following error:

> error: system does not fully support snapd: cannot mount squashfs image using "squashfs": mount:
>        /tmp/sanity-mountpoint-573191352: mount failed: Unknown error -1

This OS is based on Ubuntu core so I was expecting it will support snap, It would be nice if you will add the support out of the box.

**Comment by friendlyarm** [comment]
try: 
rm -f /var/lib/dpkg/lock-frontend

**Comment by guyluz11** [comment]
After reinstalling Friendlycore OS  I get different error.

```
Reading package lists... Done
Building dependency tree       
Reading state information... Done
Suggested packages:
  zenity | kdialog
The following NEW packages will be installed:
  snapd
0 upgraded, 1 newly installed, 0 to remove and 0 not upgraded.
Need to get 11.6 MB of archives.
After this operation, 61.1 MB of additional disk space will be used.
Get:1 http://ports.ubuntu.com/ubuntu-ports xenial-updates/main arm64 snapd arm64 2.38 [11.6 MB]
Fetched 11.6 MB in 6s (1,874 kB/s)                                                                                                                         
debconf: delaying package configuration, since apt-utils is not installed
Selecting previously unselected package snapd.
(Reading database ... 43099 files and directories currently installed.)
Preparing to unpack .../archives/snapd_2.38_arm64.deb ...
Unpacking snapd (2.38) ...
Processing triggers for mime-support (3.59ubuntu1) ...
Setting up snapd (2.38) ...
md5sum: /etc/apparmor.d/usr.lib.snapd.snap-confine: No such file or directory
snapd.failure.service is a disabled or a static unit, not starting it.
snapd.snap-repair.service is a disabled or a static unit, not starting it.

```

snap install return:

```
error: system does not fully support snapd: cannot mount squashfs image using "squashfs": mount:
       unknown filesystem type 'squashfs'

```

**Comment by guyluz11** [comment]
After installing `apt-utils` the error is:
```
Reading package lists... Done
Building dependency tree       
Reading state information... Done
The following additional packages will be installed:
  libfuse2 liblzo2-2 squashfs-tools
Suggested packages:
  fuse
The following NEW packages will be installed:
  libfuse2 liblzo2-2 snapd squashfs-tools
0 upgraded, 4 newly installed, 0 to remove and 0 not upgraded.
Need to get 0 B/11.8 MB of archives.
After this operation, 61.9 MB of additional disk space will be used.
Do you want to continue? [Y/n] Y
Selecting previously unselected package liblzo2-2:arm64.
(Reading database ... 44873 files and directories currently installed.)
Preparing to unpack .../liblzo2-2_2.08-1.2_arm64.deb ...
Unpacking liblzo2-2:arm64 (2.08-1.2) ...
Selecting previously unselected package libfuse2:arm64.
Preparing to unpack .../libfuse2_2.9.4-1ubuntu3.1_arm64.deb ...
Unpacking libfuse2:arm64 (2.9.4-1ubuntu3.1) ...
Selecting previously unselected package squashfs-tools.
Preparing to unpack .../squashfs-tools_1%3a4.3-3ubuntu2.16.04.3_arm64.deb ...
Unpacking squashfs-tools (1:4.3-3ubuntu2.16.04.3) ...
Selecting previously unselected package snapd.
Preparing to unpack .../archives/snapd_2.38_arm64.deb ...
Unpacking snapd (2.38) ...
Processing triggers for libc-bin (2.23-0ubuntu11) ...
Processing triggers for mime-support (3.59ubuntu1) ...
Setting up liblzo2-2:arm64 (2.08-1.2) ...
Setting up libfuse2:arm64 (2.9.4-1ubuntu3.1) ...
Setting up squashfs-tools (1:4.3-3ubuntu2.16.04.3) ...
Setting up snapd (2.38) ...
md5sum: /etc/apparmor.d/usr.lib.snapd.snap-confine: No such file or directory
snapd.failure.service is a disabled or a static unit, not starting it.
snapd.snap-repair.service is a disabled or a static unit, not starting it.
Processing triggers for libc-bin (2.23-0ubuntu11) ...
```

**Comment by guyluz11** [comment]
Tried [this](https://askubuntu.com/questions/1143436/snap-not-working) but still not working.
`sudo mkdir /etc/environment.d`

`sudo echo -e "PATH="/usr/local/bin:/usr/local/sbin:/usr/bin:/usr/sbin:/bin:/sbin:/snap/bin"\nXDG_DATA_DIRS="/usr/local/share:/usr/share:/var/lib/snapd/desktop"" > /etc/environment.d/60-snap-icons-and-bin.conf`

`sudo reboot now `


Error:

> Reading package lists... Done
> Building dependency tree       
> Reading state information... Done
> The following NEW packages will be installed:
>   snapd
> 0 upgraded, 1 newly installed, 0 to remove and 0 not upgraded.
> Need to get 0 B/11.6 MB of archives.
> After this operation, 61.1 MB of additional disk space will be used.
> Selecting previously unselected package snapd.
> (Reading database ... 44902 files and directories currently installed.)
> Preparing to unpack .../archives/snapd_2.38_arm64.deb ...
> Unpacking snapd (2.38) ...
> Processing triggers for mime-support (3.59ubuntu1) ...
> Setting up snapd (2.38) ...
> md5sum: /etc/apparmor.d/usr.lib.snapd.snap-confine: No such file or directory
> snapd.failure.service is a disabled or a static unit, not starting it.
> snapd.snap-repair.service is a disabled or a static unit, not starting it.
>

**Comment by guyluz11** [comment]
Found out that the only OS installation file that is working properly for my NanoPi NEO**2**  is from [here](https://www.mediafire.com/folder/ah4i6w029912b/Nano-Pi-NEO2) which I could not find by searching, this link is from the physical guide that came with the package. 
And you need to choose the  friendlycore OS with kernel 4.
From there it was updating, upgrading, and installing snapd.

On my NanoPi NEO with installation from [here](http://www.mediafire.com/folder/n5o8ihvqhnf6s/Nanopi-NEO)  it did not worked.
